Added All Tracks view and Download All Tracks functionality
leinelissen/jellyfin-audio-player pull request #75
Opened 2022-04-07 20:00 UTC by Cj1m

Added All Tracks view to allow users to see all their tracks from singles and albums
Added Download All functionality
Added album art to TrackPopupMenu

2022-04-09 14:15 UTC, leinelissen requested changes
Hey @Cj1m, thanks for your amazing contribution! I see you were able to figure out most of the codebase by yourself. I've put together some suggestions that should make your contribution perform well and be more consistent with the rest of the UI. If you could take a look at integrating the suggested changes, I'm happy to merge and release it.

2022-04-09 14:15 UTC, leinelissen commented on src/screens/Music/stacks/RecentAlbums.tsx
> +            <ListButton onPress={handleSinglesClick}>{t('all-tracks')}</ListButton>
Let's make references to `All Tracks` into just `Tracks`. The reason why All Albums is called this way is because the default Music screen shows only recent albums.

2022-04-09 14:15 UTC, leinelissen commented on src/components/SingleImage.ts
> +    border-radius: 0px;
For consistency with other images, this should have a border-radius of about 8px.

2022-04-09 14:15 UTC, leinelissen commented on src/components/SingleImage.ts
> +import styled from 'styled-components/native';
Since this file (`SingleImage`) is only used in conjunction with the tracks view, it should be located in the same directory (i.e. `src/screens/Music/stacks/components`), rather than in the global components directory (this is used for re-usable components across multiple screens).

2022-04-09 14:15 UTC, leinelissen commented on src/screens/Music/stacks/Singles.tsx
> +import { useRoute, RouteProp } from '@react-navigation/native';
This import (and a bunch of others in this file) is unused. Please remove any unused imports. Please check the output of `npm run lint` as well.

2022-04-09 14:15 UTC, leinelissen commented on src/screens/Music/stacks/components/SinglesListView.tsx
> +const SingleInformationContainer = styled.View`
This variable is unused.

2022-04-09 14:15 UTC, leinelissen commented on src/screens/Music/stacks/components/SinglesListView.tsx
> +        <ScrollView
Please use a FlatList, as huge music libraries have a ton of trouble with rendering large libraries.

2022-04-09 14:15 UTC, leinelissen commented on src/screens/Music/stacks/components/SinglesListView.tsx
> +                                    <SingleImage source={{ uri: getImage(String(tracks[trackId]?.AlbumId)) }} style={defaultStyles.imageBackground} /> :
I think it works better for the design if you make the image a bit smaller (look at the Search screen for an example). This leaves a bit more tracks in view, which makes it easier to scroll through a large library.

2022-04-09 14:15 UTC, leinelissen commented on src/screens/Music/stacks/components/SinglesListView.tsx
> +                                    numberOfLines={2}
It's probably best for performance to keep this to a single line

2022-04-09 14:15 UTC, leinelissen commented on src/screens/Music/stacks/components/SinglesListView.tsx
> +    flex-direction: row;
If you add `align-items: center;` here, all the individual parts will be nicely aligned.

2022-04-09 14:15 UTC, leinelissen commented on src/screens/Music/stacks/components/SinglesListView.tsx
> +                    <WrappableButton
It's probably best to put this up top, as it takes a really long time to scroll down (and find it) if your library is huge.

2022-04-09 14:15 UTC, leinelissen commented on src/store/music/index.ts
> +        byPlaylist: {}
The trailing comma is supposed to be here 😅

2023-09-14 23:29 UTC, nbabanov commented
@leinelissen  I can fork @Cj1m's repo and fix the mentioned issues. Would then accept the new MR(PR)?

2023-09-18 09:56 UTC, leinelissen commented
Yes, that would be greatly appreciated!

2024-07-25 14:49 UTC, closed without merging